export interface Exercise {
  id: string;
  day: number;
  muscleGroup: string;
  exerciseType: string;
  stimuloTecnica: string;
}

export const MUSCLE_GROUPS = [
  { name: "ABDUTTORI (TFL)", color: "abduttori-tfl" },
  { name: "ADDUTTORI", color: "adduttori" },
  { name: "ATTIVAZIONE", color: "attivazione" },
  { name: "AVAMBRACCI (FLESSORI / ESTENSORI)", color: "avambracci-flessori-estensori" },
  { name: "BICIPITE ACCORCIAMENTO", color: "bicipite-accorciamento" },
  { name: "BICIPITE ALLUNGAMENTO", color: "bicipite-allungamento" },
  { name: "BICIPITI", color: "bicipiti" },
  { name: "BRACHIALE", color: "brachiale" },
  { name: "BRACHIORADIALE", color: "brachioradiale" },
  { name: "CENTRO SCHIENA", color: "centro-schiena" },
  { name: "CORE / ADDOME", color: "core-addome" },
  { name: "CUFFIA DEI ROTATORI (SOVRASPINATO, SOTTOSPINATO, PICCOLO ROTONDO, SOTTOSCAPOLARE)", color: "cuffia-rotatori" },
  { name: "DELTOIDE ANTERIORE", color: "deltoide-anteriore" },
  { name: "DELTOIDE MEDIALE", color: "deltoide-mediale" },
  { name: "DELTOIDE POSTERIORE", color: "deltoide-posteriore" },
  { name: "DELTOIDI", color: "deltoidi" },
  { name: "DEPRESSORI SCAPOLARI (TRAPEZIO INFERIORE, GRAN DORSALE, GRAN PETTORALE INFERIORE)", color: "depressori-scapolari" },
  { name: "DORSO (AMPIEZZA)", color: "dorso-ampiezza" },
  { name: "DORSO (SPESSORE)", color: "dorso-spessore" },
  { name: "ELEVATORE DELLA SCAPOLA", color: "elevatore-scapola" },
  { name: "ERETTORI SPINALI", color: "erettori-spinali" },
  { name: "FEMORALI", color: "femorali" },
  { name: "FEMORALI + GLUTEI", color: "femorali-glutei" },
  { name: "FLESSORI DITA / PRESA (GRUPPO AVAMBRACCIO)", color: "flessori-dita-presa" },
  { name: "GASTROCNEMIO (MEDIALE/LATERALE)", color: "gastrocnemio" },
  { name: "GLUTEI", color: "glutei" },
  { name: "GRAN DORSALE", color: "gran-dorsale" },
  { name: "GRAN ROTONDO", color: "gran-rotondo" },
  { name: "GRANDE GLUTEO", color: "grande-gluteo" },
  { name: "ILEO-PSOAS / FLESSORI ANCA", color: "ileo-psoas" },
  { name: "MEDIO GLUTEO", color: "medio-gluteo" },
  { name: "MULTIFIDI", color: "multifidi" },
  { name: "OBLIQUI", color: "obliqui" },
  { name: "PERONEI (FIBULARI)", color: "peronei" },
  { name: "PETTORALE ADDOMINALE", color: "pettorale-addominale" },
  { name: "PETTORALE CLAVICOLARE", color: "pettorale-clavic" },
  { name: "PETTORALE STERNALE", color: "pettorale-sternale" },
  { name: "PETTORALI", color: "pettorali" },
  { name: "PICCOLO GLUTEO", color: "piccolo-gluteo" },
  { name: "POLPACCI", color: "polpacci" },
  { name: "PROTRATTORI SCAPOLARI (SERRATO ANTERIORE, PETTORALE MINORE)", color: "protrattori-scapolari" },
  { name: "QUADRATO DEI LOMBI", color: "quadrato-lombi" },
  { name: "QUADRICIPITI", color: "quadricipiti" },
  { name: "QUADRICIPITI + GLUTEI", color: "quadricipiti-glutei" },
  { name: "RETRATTORI SCAPOLARI (ROMBOIDI + TRAPEZIO MEDIO)", color: "retrattori-scapolari" },
  { name: "ROMBOIDI", color: "romboidi" },
  { name: "ROTATORI DELL’ANCA (PIRIFORME, OTTURATORE, GEMELLI)", color: "rotatori-anca" },
  { name: "SERRATO ANTERIORE", color: "serrato-anteriore" },
  { name: "SOLEO", color: "soleo" },
  { name: "TIBIALE ANTERIORE", color: "tibiale-anteriore" },
  { name: "TIBIALE POSTERIORE", color: "tibiale-posteriore" },
  { name: "TRAPEZIO", color: "trapezio" },
  { name: "TRAPEZIO + ROMBOIDI", color: "trapezio-romboidi" },
  { name: "TRAPEZIO INFERIORE", color: "trapezio-inferiore" },
  { name: "TRAPEZIO MEDIO", color: "trapezio-medio" },
  { name: "TRAPEZIO SUPERIORE", color: "trapezio-superiore" },
  { name: "TRASVERSO ADDOME", color: "trasverso-addome" },
  { name: "TRICIPITE ACCORCIAMENTO", color: "tricipite-accorciamento" },
  { name: "TRICIPITE ALLUNGAMENTO", color: "tricipite-allungamento" },
  { name: "TRICIPITI", color: "tricipiti" },
  { name: "ACCOSCIATA (KNEE-DOMINANT)", color: "accosciata" },
  { name: "ANTI-ESTENSIONE", color: "anti-estensione" },
  { name: "ANTI-INCLINAZIONE LATERALE", color: "anti-inclinazione-laterale" },
  { name: "ANTI-ROTAZIONE", color: "anti-rotazione" },
  { name: "CARRIES / PORTATE", color: "carries-portate" },
  { name: "DEPRESSIONE SCAPOLARE", color: "depressione-scapolare" },
  { name: "DORSIFLESSIONE", color: "dorsiflessione" },
  { name: "ESTENSIONE GINOCCHIO (ISOLATA)", color: "estensione-ginocchio" },
  { name: "FLESSIONE GINOCCHIO (ISOLATA)", color: "flessione-ginocchio" },
  { name: "FLESSIONE PLANTARE", color: "flessione-plantare" },
  { name: "HIP HINGE (FLESSIONE D’ANCA)", color: "hip-hinge" },
  { name: "LOCOMOZIONE / SLED", color: "locomozione-sled" },
  { name: "LUNGES / UNILATERALI", color: "lunges-unilaterali" },
  { name: "PROTRAZIONE SCAPOLARE", color: "protrazione-scapolare" },
  { name: "RETRAZIONE SCAPOLARE", color: "retrazione-scapolare" },
  { name: "ROTAZIONE SCAPOLARE VERSO L’ALTO", color: "rotazione-scapolare-alto" },
  { name: "SPINTA D’ANCA", color: "spinta-anca" },
  { name: "SPINTA ORIZZONTALE", color: "spinta-orizzontale" },
  { name: "SPINTA VERTICALE", color: "spinta-verticale" },
  { name: "TIRATE OLY", color: "tirate-oly" },
  { name: "TRAZIONE ORIZZONTALE", color: "trazione-orizzontale" },
  { name: "TRAZIONE VERTICALE", color: "trazione-verticale" },
  { name: "VARIANTI POWERLIFTING", color: "varianti-powerlifting" },
  { name: "MOBILITÀ ANCA", color: "mobilita-anca" },
  { name: "MOBILITÀ CAVIGLIA", color: "mobilita-caviglia" },
  { name: "MOBILITÀ COLONNA LOMBARE (CONTROLLO)", color: "mobilita-colonna-lombare" },
  { name: "MOBILITÀ POLSO/AVAMBRACCIO", color: "mobilita-polso-avambraccio" },
  { name: "MOBILITÀ SPALLA", color: "mobilita-spalla" },
  { name: "MOBILITÀ TORACICA", color: "mobilita-toracica" },
  { name: "PREHAB ANCA/GLUTEI", color: "prehab-anca-glutei" },
  { name: "PREHAB CAVIGLIA/TENDINE D’ACHILLE", color: "prehab-caviglia" },
  { name: "PREHAB COLONNA (McGill Big 3)", color: "prehab-colonna" },
  { name: "PREHAB GINOCCHIO (PFPS/TENDINI - GENERICO)", color: "prehab-ginocchio" },
  { name: "PREHAB GOMITO/POLSO", color: "prehab-gomito-polso" },
  { name: "PREHAB SPALLA (CUFFIA/SCAPOLA)", color: "prehab-spalla" },
];

export const STIMOLI = [
  "Densità - AFAP / For time",
  "Densità - AMRAP a tempo",
  "Densità - Accumulo ad onda di densità",
  "Densità - Accumulo lineare di densità",
  "Densità - Circuiti a time-cap",
  "Densità - EDT (Escalating Density Training)",
  "Densità - EMOM / E2MOM",
  "Fatica/Pianificazione - Deload",
  "Fatica/Pianificazione - MEV/MAV/MRV",
  "Fatica/Pianificazione - Overreaching (funzionale/non)",
  "Fatica/Pianificazione - Resensitization / Pivot",
  "Fatica/Pianificazione - SFR (Stimulus to Fatigue Ratio)",
  "Fatica/Pianificazione - Set/Rep cap / Quality cap",
  "Fatica/Pianificazione - Taper",
  "Intensificazione - BFR / Occlusione (KAATSU)",
  "Intensificazione - Bande/Catene (Accommodating resistance)",
  "Intensificazione - Contrast load",
  "Intensificazione - Loaded stretch / Weighted stretch",
  "Intensificazione - Negative/Forced/Cheat controllato",
  "Intensificazione - PAP / Complex / French contrast",
  "Intensificazione - Partial ROM programmato",
  "Progressioni - A blocchi (Accumulo → Intensificazione → Trasmutazione/Peaking)",
  "Progressioni - A gradini (Step loading)",
  "Progressioni - A onde del carico (Wave loading)",
  "Progressioni - Autoregolata (RPE/RIR/APRE)",
  "Progressioni - Bulgarian / Daily max",
  "Progressioni - Coniugata (Westside)",
  "Progressioni - Emerging strategies (RTS)",
  "Progressioni - Lineare (del carico)",
  "Progressioni - Lineare inversa (reverse)",
  "Progressioni - Ondulata giornaliera/settimanale (DUP/WUP)",
  "Progressioni - Peaking/Taper",
  "Progressioni - Pendolare",
  "Progressioni - VBT / Velocity-loss",
  "Set/Rep - Cluster",
  "Set/Rep - Descending / Reverse pyramid",
  "Set/Rep - Drop / Strip set",
  "Set/Rep - Giant set",
  "Set/Rep - Ladder",
  "Set/Rep - Mechanical drop set",
  "Set/Rep - Myo-reps",
  "Set/Rep - Piramidale classico",
  "Set/Rep - Post-exhaust",
  "Set/Rep - Pre-exhaust",
  "Set/Rep - Ramping / Ascending",
  "Set/Rep - Rep-goal / Double progression",
  "Set/Rep - Rest-pause (DC)",
  "Set/Rep - Serie dritte (Straight sets)",
  "Set/Rep - Set a cedimento (tecnico/assoluto)",
  "Set/Rep - Superset",
  "Set/Rep - Top set + Back-off",
  "Set/Rep - Triset",
  "Tempo/TUT - 1¼ / 1½ reps",
  "Tempo/TUT - Eccentrica sovraccaricata",
  "Tempo/TUT - Pause/fermi isometrici",
  "Tempo/TUT - Tempo training (es. 4-0-1-0)",
  "Tempo/TUT - Tempo waves",
];
